/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BankRouteImport } from './routes/bank'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard/approvals'
import { Route as DashboardAuditRouteImport } from './routes/dashboard/audit'
import { Route as DashboardAuditLogsRouteImport } from './routes/dashboard/audit-logs'
import { Route as DashboardComplianceRouteImport } from './routes/dashboard/compliance'
import { Route as DashboardEscalationsRouteImport } from './routes/dashboard/escalations'
import { Route as DashboardGraphRouteImport } from './routes/dashboard/graph'
import { Route as DashboardInsiderRouteImport } from './routes/dashboard/insider'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard/integrations'
import { Route as DashboardInvestigationRouteImport } from './routes/dashboard/investigation'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardRiskRouteImport } from './routes/dashboard/risk'
import { Route as DashboardRolesRouteImport } from './routes/dashboard/roles'
import { Route as DashboardSecurityRouteImport } from './routes/dashboard/security'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardThreatRouteImport } from './routes/dashboard/threat'
import { Route as DashboardThreatsRouteImport } from './routes/dashboard/threats'
import { Route as DashboardUsersRouteImport } from './routes/dashboard/users'
import { Route as DashboardCasesIndexRouteImport } from './routes/dashboard/cases/index'
import { Route as DashboardCasesCaseIdRouteImport } from './routes/dashboard/cases/$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/dashboard/approvals',
  path: '/dashboard/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuditRoute = DashboardAuditRouteImport.update({
  id: '/dashboard/audit',
  path: '/dashboard/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/dashboard/audit-logs',
  path: '/dashboard/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardComplianceRoute = DashboardComplianceRouteImport.update({
  id: '/dashboard/compliance',
  path: '/dashboard/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardEscalationsRoute = DashboardEscalationsRouteImport.update({
  id: '/dashboard/escalations',
  path: '/dashboard/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGraphRoute = DashboardGraphRouteImport.update({
  id: '/dashboard/graph',
  path: '/dashboard/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInsiderRoute = DashboardInsiderRouteImport.update({
  id: '/dashboard/insider',
  path: '/dashboard/insider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/dashboard/integrations',
  path: '/dashboard/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInvestigationRoute = DashboardInvestigationRouteImport.update({
  id: '/dashboard/investigation',
  path: '/dashboard/investigation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRiskRoute = DashboardRiskRouteImport.update({
  id: '/dashboard/risk',
  path: '/dashboard/risk',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRolesRoute = DashboardRolesRouteImport.update({
  id: '/dashboard/roles',
  path: '/dashboard/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSecurityRoute = DashboardSecurityRouteImport.update({
  id: '/dashboard/security',
  path: '/dashboard/security',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardThreatRoute = DashboardThreatRouteImport.update({
  id: '/dashboard/threat',
  path: '/dashboard/threat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardThreatsRoute = DashboardThreatsRouteImport.update({
  id: '/dashboard/threats',
  path: '/dashboard/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/dashboard/users',
  path: '/dashboard/users',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCasesIndexRoute = DashboardCasesIndexRouteImport.update({
  id: '/dashboard/cases/',
  path: '/dashboard/cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCasesCaseIdRoute = DashboardCasesCaseIdRouteImport.update({
  id: '/dashboard/cases/$caseId',
  path: '/dashboard/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/escalations': typeof DashboardEscalationsRoute
  '/dashboard/graph': typeof DashboardGraphRoute
  '/dashboard/insider': typeof DashboardInsiderRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/investigation': typeof DashboardInvestigationRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/threat': typeof DashboardThreatRoute
  '/dashboard/threats': typeof DashboardThreatsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/escalations': typeof DashboardEscalationsRoute
  '/dashboard/graph': typeof DashboardGraphRoute
  '/dashboard/insider': typeof DashboardInsiderRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/investigation': typeof DashboardInvestigationRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/threat': typeof DashboardThreatRoute
  '/dashboard/threats': typeof DashboardThreatsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/cases': typeof DashboardCasesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bank': typeof BankRoute
  '/sign-in': typeof SignInRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/audit': typeof DashboardAuditRoute
  '/dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/dashboard/compliance': typeof DashboardComplianceRoute
  '/dashboard/escalations': typeof DashboardEscalationsRoute
  '/dashboard/graph': typeof DashboardGraphRoute
  '/dashboard/insider': typeof DashboardInsiderRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/investigation': typeof DashboardInvestigationRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/risk': typeof DashboardRiskRoute
  '/dashboard/roles': typeof DashboardRolesRoute
  '/dashboard/security': typeof DashboardSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/threat': typeof DashboardThreatRoute
  '/dashboard/threats': typeof DashboardThreatsRoute
  '/dashboard/users': typeof DashboardUsersRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/cases/$caseId': typeof DashboardCasesCaseIdRoute
  '/dashboard/cases/': typeof DashboardCasesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bank'
    | '/sign-in'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/audit-logs'
    | '/dashboard/compliance'
    | '/dashboard/escalations'
    | '/dashboard/graph'
    | '/dashboard/insider'
    | '/dashboard/integrations'
    | '/dashboard/investigation'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/roles'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/threat'
    | '/dashboard/threats'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/cases/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bank'
    | '/sign-in'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/audit-logs'
    | '/dashboard/compliance'
    | '/dashboard/escalations'
    | '/dashboard/graph'
    | '/dashboard/insider'
    | '/dashboard/integrations'
    | '/dashboard/investigation'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/roles'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/threat'
    | '/dashboard/threats'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/cases/$caseId'
    | '/dashboard/cases'
  id:
    | '__root__'
    | '/'
    | '/bank'
    | '/sign-in'
    | '/dashboard/approvals'
    | '/dashboard/audit'
    | '/dashboard/audit-logs'
    | '/dashboard/compliance'
    | '/dashboard/escalations'
    | '/dashboard/graph'
    | '/dashboard/insider'
    | '/dashboard/integrations'
    | '/dashboard/investigation'
    | '/dashboard/reports'
    | '/dashboard/risk'
    | '/dashboard/roles'
    | '/dashboard/security'
    | '/dashboard/settings'
    | '/dashboard/threat'
    | '/dashboard/threats'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/cases/$caseId'
    | '/dashboard/cases/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BankRoute: typeof BankRoute
  SignInRoute: typeof SignInRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardAuditRoute: typeof DashboardAuditRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardComplianceRoute: typeof DashboardComplianceRoute
  DashboardEscalationsRoute: typeof DashboardEscalationsRoute
  DashboardGraphRoute: typeof DashboardGraphRoute
  DashboardInsiderRoute: typeof DashboardInsiderRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardInvestigationRoute: typeof DashboardInvestigationRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardRiskRoute: typeof DashboardRiskRoute
  DashboardRolesRoute: typeof DashboardRolesRoute
  DashboardSecurityRoute: typeof DashboardSecurityRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardThreatRoute: typeof DashboardThreatRoute
  DashboardThreatsRoute: typeof DashboardThreatsRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCasesCaseIdRoute: typeof DashboardCasesCaseIdRoute
  DashboardCasesIndexRoute: typeof DashboardCasesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/dashboard/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audit': {
      id: '/dashboard/audit'
      path: '/dashboard/audit'
      fullPath: '/dashboard/audit'
      preLoaderRoute: typeof DashboardAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audit-logs': {
      id: '/dashboard/audit-logs'
      path: '/dashboard/audit-logs'
      fullPath: '/dashboard/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/compliance': {
      id: '/dashboard/compliance'
      path: '/dashboard/compliance'
      fullPath: '/dashboard/compliance'
      preLoaderRoute: typeof DashboardComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/escalations': {
      id: '/dashboard/escalations'
      path: '/dashboard/escalations'
      fullPath: '/dashboard/escalations'
      preLoaderRoute: typeof DashboardEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/graph': {
      id: '/dashboard/graph'
      path: '/dashboard/graph'
      fullPath: '/dashboard/graph'
      preLoaderRoute: typeof DashboardGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/insider': {
      id: '/dashboard/insider'
      path: '/dashboard/insider'
      fullPath: '/dashboard/insider'
      preLoaderRoute: typeof DashboardInsiderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/dashboard/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/investigation': {
      id: '/dashboard/investigation'
      path: '/dashboard/investigation'
      fullPath: '/dashboard/investigation'
      preLoaderRoute: typeof DashboardInvestigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/risk': {
      id: '/dashboard/risk'
      path: '/dashboard/risk'
      fullPath: '/dashboard/risk'
      preLoaderRoute: typeof DashboardRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/roles': {
      id: '/dashboard/roles'
      path: '/dashboard/roles'
      fullPath: '/dashboard/roles'
      preLoaderRoute: typeof DashboardRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/security': {
      id: '/dashboard/security'
      path: '/dashboard/security'
      fullPath: '/dashboard/security'
      preLoaderRoute: typeof DashboardSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/threat': {
      id: '/dashboard/threat'
      path: '/dashboard/threat'
      fullPath: '/dashboard/threat'
      preLoaderRoute: typeof DashboardThreatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/threats': {
      id: '/dashboard/threats'
      path: '/dashboard/threats'
      fullPath: '/dashboard/threats'
      preLoaderRoute: typeof DashboardThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/users': {
      id: '/dashboard/users'
      path: '/dashboard/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cases/': {
      id: '/dashboard/cases/'
      path: '/dashboard/cases'
      fullPath: '/dashboard/cases/'
      preLoaderRoute: typeof DashboardCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/cases/$caseId': {
      id: '/dashboard/cases/$caseId'
      path: '/dashboard/cases/$caseId'
      fullPath: '/dashboard/cases/$caseId'
      preLoaderRoute: typeof DashboardCasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BankRoute: BankRoute,
  SignInRoute: SignInRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardAuditRoute: DashboardAuditRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardComplianceRoute: DashboardComplianceRoute,
  DashboardEscalationsRoute: DashboardEscalationsRoute,
  DashboardGraphRoute: DashboardGraphRoute,
  DashboardInsiderRoute: DashboardInsiderRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardInvestigationRoute: DashboardInvestigationRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardRiskRoute: DashboardRiskRoute,
  DashboardRolesRoute: DashboardRolesRoute,
  DashboardSecurityRoute: DashboardSecurityRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardThreatRoute: DashboardThreatRoute,
  DashboardThreatsRoute: DashboardThreatsRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCasesCaseIdRoute: DashboardCasesCaseIdRoute,
  DashboardCasesIndexRoute: DashboardCasesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
